export const ROUTE_PATHS = {
  root: '/',
  controlMonitoring: '/control/monitoring',
  controlMultiRobotMonitoring: '/control/monitoring/multi',
  controlRobotMonitoring: '/control/monitoring/:robotId',
  controlInterventions: '/control/interventions',
  controlRobots: '/control/robots',
  controlSites: '/control/sites',
  controlCoordinates: '/control/coordinates',
  controlEvents: '/control/events',
  controlReports: '/control/reports',
  controlSettings: '/control/settings',
  mlopsCapture: '/mlops/capture',
  mlopsSessions: '/mlops/sessions',
  mlopsSessionDetail: '/mlops/sessions/:sessionId',
  mlopsEpisodes: '/mlops/episodes',
  mlopsEpisodeDetail: '/mlops/episodes/:episodeId',
  mlopsDatasets: '/mlops/datasets',
  mlopsNewDataset: '/mlops/datasets/new',
  mlopsDatasetDetail: '/mlops/datasets/:datasetId',
  mlopsSettings: '/mlops/settings',
  bigdataOverview: '/bigdata/overview',
  bigdataExplorer: '/bigdata/explorer',
  bigdataSettings: '/bigdata/settings',
} as const;
